Update README.md
awslabs/wdio-aws-device-farm-service pull request #26
Opened 2022-09-21 11:45 UTC by halit-carbon

Added. Note: this service only supports desktop browser testing

_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-21 12:01 UTC, JavierLuna requested changes

2022-09-21 12:01 UTC, JavierLuna commented on README.md
> +Note: this service only supports desktop browser testing
Hi! Thank you for your contribution.

To make the clarification more visible, I was thinking that maybe we could extend the project's description (the one on line 3) with it instead of including it in the Example section.

2022-09-21 12:58 UTC, halit-carbon commented on README.md
> +Note: this service only supports desktop browser testing
yes you are right.  changed

2022-09-21 14:33 UTC, JavierLuna approved these changes
LGTM

2022-09-22 07:14 UTC, merged

2022-09-22 07:14 UTC, JavierLuna commented
Merged, thank you again for your contribution!